/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfase;

/**
 *
 * @author Oshan Demel
 */
public class ExamTable extends javax.swing.JPanel {

    /**
     * Creates new form ExamTable
     */
    public ExamTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelExamTable = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddaplicant = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonCertificate = new javax.swing.JButton();
        jButtonAddAplicant = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxSearchaplicant = new javax.swing.JComboBox<>();
        jTextAplicant = new javax.swing.JTextField();

        jPanelExamTable.setBackground(new java.awt.Color(102, 102, 255));

        jPanelTitle.setBackground(new java.awt.Color(102, 102, 255));
        jPanelTitle.setPreferredSize(new java.awt.Dimension(948, 82));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mpma.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableAddaplicant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAddaplicant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAddaplicantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAddaplicant);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jButtonCertificate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCertificate.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonCertificate.setForeground(new java.awt.Color(204, 51, 0));
        jButtonCertificate.setText("Certifiacate");
        jButtonCertificate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51), null, null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jButtonCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddAplicant.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddAplicant.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonAddAplicant.setForeground(new java.awt.Color(0, 0, 51));
        jButtonAddAplicant.setText("Add New Exam");
        jButtonAddAplicant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddAplicantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddAplicantMouseExited(evt);
            }
        });
        jButtonAddAplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAplicantActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Search By :-");

        ComboBoxSearchaplicant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nic", "Name", "Phone Number" }));
        ComboBoxSearchaplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSearchaplicantActionPerformed(evt);
            }
        });

        jTextAplicant.setBackground(new java.awt.Color(204, 255, 255));
        jTextAplicant.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jTextAplicant.setForeground(new java.awt.Color(51, 0, 51));
        jTextAplicant.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextAplicant.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextAplicantCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanelExamTableLayout = new javax.swing.GroupLayout(jPanelExamTable);
        jPanelExamTable.setLayout(jPanelExamTableLayout);
        jPanelExamTableLayout.setHorizontalGroup(
            jPanelExamTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExamTableLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelExamTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExamTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddAplicant)
                .addGap(87, 87, 87))
            .addGroup(jPanelExamTableLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(ComboBoxSearchaplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jTextAplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        jPanelExamTableLayout.setVerticalGroup(
            jPanelExamTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExamTableLayout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelExamTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxSearchaplicant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAplicant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddAplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExamTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExamTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAddaplicantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAddaplicantMouseClicked

//        if (jTableAddaplicant.getSelectedRowCount() == 1) {
//
//            ADAF.setVisible(true);
//
//            try {
//
//                Field fieldId = ADAF.getClass().getDeclaredField("txtId");
//                fieldId.setAccessible(true);
//                JTextField txtId = (JTextField) fieldId.get(ADAF);
//                txtId.setText(AddAplicantModel.getValueAt(jTableAddaplicant.getSelectedRow(), 0).toString());
//
//                Field field = ADAF.getClass().getDeclaredField("txtNic");
//                field.setAccessible(true);
//                JTextField txtNic = (JTextField) field.get(ADAF);
//                txtNic.setText(AddAplicantModel.getValueAt(jTableAddaplicant.getSelectedRow(), 1).toString());
//
//                Field nameFiled = ADAF.getClass().getDeclaredField("txtName");
//                nameFiled.setAccessible(true);
//                JTextField txtName = (JTextField) nameFiled.get(ADAF);
//                txtName.setText(AddAplicantModel.getValueAt(jTableAddaplicant.getSelectedRow(), 2).toString());
//
//                Field pnumField = ADAF.getClass().getDeclaredField("txtPhoneNumber");
//                pnumField.setAccessible(true);
//                JTextField txtPhoneNumber = (JTextField) pnumField.get(ADAF);
//                txtPhoneNumber.setText(AddAplicantModel.getValueAt(jTableAddaplicant.getSelectedRow(), 3).toString());
//
//                Field addressField = ADAF.getClass().getDeclaredField("txtAddress");
//                addressField.setAccessible(true);
//                JTextField txtAddress = (JTextField) addressField.get(ADAF);
//                txtAddress.setText(AddAplicantModel.getValueAt(jTableAddaplicant.getSelectedRow(), 4).toString());
//
//            } catch (Exception e) {
//            }
//
//        }

    }//GEN-LAST:event_jTableAddaplicantMouseClicked

    private void jButtonAddAplicantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddAplicantMouseEntered
//        jButtonAddAplicant.setForeground(ClickedColor);
//        jButtonAddAplicant.setBackground(DefaultColor);
    }//GEN-LAST:event_jButtonAddAplicantMouseEntered

    private void jButtonAddAplicantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddAplicantMouseExited
//        jButtonAddAplicant.setForeground(DefaultColor);
//        jButtonAddAplicant.setBackground(ClickedColor);
    }//GEN-LAST:event_jButtonAddAplicantMouseExited

    private void jButtonAddAplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAplicantActionPerformed

//        ADAF.setVisible(true);
    }//GEN-LAST:event_jButtonAddAplicantActionPerformed

    private void ComboBoxSearchaplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSearchaplicantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSearchaplicantActionPerformed

    private void jTextAplicantCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextAplicantCaretUpdate

//        String[] col_names = {"stu_nic", "stu_name", "stu_name", "phone_num"};
//
//        if (jTextAplicant.getText().isEmpty()) {
//            setAplicantTableData("SELECT * FROM `student_details`  ORDER BY `stu_id`");
//            jTextAplicant.setText("");
//        } else {
//
//            String col_name = col_names[ComboBoxSearchaplicant.getSelectedIndex()];
//            String value = jTextAplicant.getText();
//            String query = "SELECT * FROM `student_details` WHERE " + col_name + " LIKE '%" + value + "%'";
//
//            setAplicantTableData(query);
//
//        }

    }//GEN-LAST:event_jTextAplicantCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxSearchaplicant;
    private javax.swing.JButton jButtonAddAplicant;
    private javax.swing.JButton jButtonCertificate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelExamTable;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAddaplicant;
    private javax.swing.JTextField jTextAplicant;
    // End of variables declaration//GEN-END:variables
}
